### ISSUE TITLE
What was the issue with this approach?

### ISSUE THREAD

**Issue by cornelius-keller** [joar/disk-usage-exporter#2]
Hi @joar, 

can you maybe shortly document what was the issue with this approach?
Theoretically kubelet should export volume metrics but it does not in a lot of cases, for example if a flexvolume plugin is used as in my case.
I quickly scanned your code, and as far as I see I would just need to adapt your filter regex to get the metrics for my flexvolumes exported, but I wanted to know your general issue bevore rushing ahead.

Thanks
- Cornelius

**Comment by joar** [comment]
@cornelius-keller AFAIK it's as you say, only the filter regex needs to be adapted to support newer versions of kubernetes. You're welcome to try it out.

**Comment by joar** [comment]
My main reason for putting the :warning: in the README is that I discovered it was broken, but had not enough motivation to make it up-to-date.

**Comment by cornelius-keller** [comment]
@joar thanks for clarifying. Will try it out.
